import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      paddingTop: 30,
    },
    whiteBackground: {
      backgroundColor: "#FFFFFF",
    },
    scrollContent: {
      paddingBottom: 30,
    },
    header: {
      padding: 16,
      backgroundColor: "#FFF",
      borderBottomWidth: 1,
      borderBottomColor: "#E0E0E0",
      elevation: 2,
    },
    title: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#333",
    },
    profileSection: {
      alignItems: "center",
      backgroundColor: "#FFF",
      padding: 20,
      marginBottom: 15,
      borderRadius: 10,
      elevation: 3,
      marginHorizontal: 10,
      marginTop: 15,
    },
    profileImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      marginBottom: 10,
      borderWidth: 3,
      borderColor: "#FF9900",
    },
    profileName: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#333",
    },
    profileId: {
      fontSize: 14,
      color: "#666",
      marginTop: 5,
    },
    orderSection: {
      backgroundColor: "#FFF",
      padding: 20,
      marginBottom: 15,
      borderRadius: 15,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      marginHorizontal: 15,
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 20,
      borderBottomWidth: 2,
      borderBottomColor: "#FF9900",
      paddingBottom: 10,
    },
    statusMenu: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    statusButton: {
      alignItems: "center",
      backgroundColor: "#F5F7FA",
      borderRadius: 12,
      padding: 12,
      width: 80,
    },
    iconContainer: {
      backgroundColor: "#FF9900",
      borderRadius: 30,
      width: 60,
      height: 60,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 8,
    },
    statusText: {
      fontSize: 12,
      color: "#333",
      textAlign: "center",
      marginTop: 8,
      fontWeight: "600",
    },
    viewAllOrders: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingTop: 15,
      borderTopWidth: 1,
      borderTopColor: "#E0E0E0",
      marginTop: 10,
    },
    viewAllOrdersText: {
      fontSize: 16,
      color: "#FF9900",
      fontWeight: "bold",
    },
    settingsSection: {
      backgroundColor: "#FFF",
      padding: 16,
      borderRadius: 10,
      elevation: 3,
      marginHorizontal: 10,
    },
    settingItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#E0E0E0",
    },
    settingText: {
      flex: 1,
      fontSize: 16,
      color: "#333",
      marginLeft: 15,
    },
    logoutButton: {
      margin: 16,
      backgroundColor: "#F44336",
      padding: 15,
      borderRadius: 8,
      alignItems: "center",
      elevation: 3,
    },
    logoutText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "bold",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      backgroundColor: "#FFF",
      padding: 20,
      borderRadius: 10,
      width: "80%",
      alignItems: "center",
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 10,
      color: "#333",
    },
    modalText: {
      fontSize: 16,
      marginBottom: 20,
      textAlign: "center",
      color: "#666",
    },
    modalButtonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 10,
    },
    modalButton: {
      padding: 12,
      borderRadius: 8,
      width: "45%",
      alignItems: "center",
    },
    cancelButton: {
      backgroundColor: "#f5f5f5",
      borderWidth: 1,
      borderColor: "#ddd",
    },
    loginButton: {
      backgroundColor: "#FF9900",
    },
    cancelButtonText: {
      color: "#666",
      fontSize: 16,
      paddingHorizontal: 20,
      paddingVertical: 5,
      fontWeight: "bold",
    },
    loginButtonText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "bold",
      paddingHorizontal: 20,
      paddingVertical: 5,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
  });

  export default styles;